InchirieriMasini/Areas/Manager/Controllers/DashboardController.cs
using InchirieriMasini.DataAccess.Data;
using InchirieriMasini.DataAccess.Repository.IRepository;
using InchirieriMasini.Models;
using InchirieriMasini.Models.ViewModels;
using InchirieriMasini.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace InchirieriMasini.Areas.Manager.Controllers
{

    [Area("Manager")]
    [Authorize(Roles = StaticData.Role_Manager)]

    public class DashboardController : Controller
    {
        private ApplicationDbContext _db;
        private readonly IUnitOfWork _unitOfWork;
        public DashboardController(IUnitOfWork unitOfWork, ApplicationDbContext db)
        {
            _unitOfWork = unitOfWork;
            _db = db;
        }
        //GET
        public IActionResult Index()
        {
            DashboardVM dateDashboard = new DashboardVM();


            var totalIncasari = _db.Comenzi.Select(u => u.TotalComanda).Sum();

            var totalTranzactii = _db.Comenzi.Select(u => u.IdComanda).Count();
            var medieZile = _db.Comenzi.Select(u => u.Durata).Average();
            var numarClienti = _db.Comenzi.Select(u => u.ClientId).Distinct().Count();
            var venitMediuClient = totalIncasari / numarClienti;
            var valoareMedieComanda = totalIncasari / totalTranzactii;

            var iduriMasini = _db.Comenzi.Select(u => u.IdMasina).Distinct().ToList();
            var max = 0;
            var idMasina = 0;
            foreach (var id in iduriMasini)
            {
                var numar = _db.Comenzi.Where(u => u.IdMasina == id).Select(u => u.IdMasina).Count();
                if (numar > max)
                {
                    max = numar;
                    idMasina = id;
                }

            }
            var ceaMaiInchiriataMasina = _db.Masini.Where(u => u.IdMasina == idMasina).Select(u => u.ModelMasina);

            dateDashboard.medieZileInchiriere = medieZile;
            dateDashboard.totalIncasari = totalIncasari;
            dateDashboard.totalTranzactii = totalTranzactii;
            dateDashboard.numarClienti = numarClienti;
            dateDashboard.venitMediuPerClient = venitMediuClient;
            dateDashboard.valoareMedieComanda = valoareMedieComanda;
            dateDashboard.ceaMaiInchiriataMasina = "Audi E-Tron";


            return View(dateDashboard);
        }
        public IActionResult GraficVanzari()
        {
            //List<GraficVanzari> graficVanzari = new List<GraficVanzari>();

            //    for (int day=1; day<=DateTime.Now.Day; day++)
            //    {
            //        var label = new DateTime(DateTime.Now.Year, DateTime.Now.Month, day);

            //    var y = _db.Comenzi.Where(u => u.DataComanda.Day == day && u.DataComanda.Month == DateTime.Now.Month && u.DataComanda.Year == DateTime.Now.Year)
            //    .Select(u => u.TotalComanda).Sum();


            //        graficVanzari.Add(new GraficVanzari(label, y));

            //    };

            
            //var data = JsonConvert.SerializeObject(graficVanzari);

            return PartialView();
        }

        public IActionResult GraphicPie()
        {
            //List<GraficPie> graficPie = new List<GraficPie>();

            //for (int day = 1; day <= DateTime.Now.Day; day++)
            //{
            //    var label = new DateTime(DateTime.Now.Year, DateTime.Now.Month, day);

            //    var y = _db.Comenzi.Where(u => u.DataComanda.Day == day && u.DataComanda.Month == DateTime.Now.Month && u.DataComanda.Year == DateTime.Now.Year)
            //    .Select(u => u.TotalComanda).Sum();


            //    graficVanzari.Add(new GraficVanzari(label, y));

            //};


            //var data = JsonConvert.SerializeObject(graficVanzari);

            return PartialView();
        }

        public IActionResult Comenzi()
        {

            return View();
        }
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<Comanda> comenzi;
            comenzi = _unitOfWork.Comanda.GetAll(includeProperties: "ApplicationUser,Client,Masina");
            return Json(new { data = comenzi });
        }
        #endregion

    }
}

InchirieriMasini/Areas/Manager/Controllers/MasinaController.cs
using InchirieriMasini.DataAccess.Data;
using InchirieriMasini.DataAccess.Repository.IRepository;
using InchirieriMasini.Models;
using InchirieriMasini.Models.ViewModels;
using InchirieriMasini.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace InchirieriMasini.Areas.Manager.Controllers;

[Area("Manager")]
[Authorize(Roles = StaticData.Role_Manager )]
public class MasinaController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;

    public MasinaController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
    }
    public IActionResult Index()
    {

        return View();
    }

    //GET
    public IActionResult Upsert(int? IdMasina)
    {
        MasinaVM masinaVM = new MasinaVM()
        {
            Masina = new(),
            ListaMarci = _unitOfWork.MarcaMasina.GetAll().Select(i => new SelectListItem
            {
                Text = i.DenumireMarca,
                Value = i.IdMarca.ToString()
            })
        };
        if (IdMasina == null || IdMasina == 0)
        {
            return View(masinaVM);
        }
        else
        {
            masinaVM.Masina = _unitOfWork.Masina.GetFirstOrDefault(u => u.IdMasina == IdMasina);
            return View(masinaVM);
        }
    }
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(MasinaVM obj, IFormFile? file1, IFormFile? file2, IFormFile? file3)
    {
        if (ModelState.IsValid)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;
            if (file1 != null)
            {
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRootPath, @"Imagini/Masini/");
                var extension = Path.GetExtension(file1.FileName);

                if (obj.Masina.ImagineMasina1 != null)
                {
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Masina.ImagineMasina1.TrimStart('/'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }


                using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file1.CopyTo(fileStream);
                }
                obj.Masina.ImagineMasina1 = @"/Imagini/Masini/" + fileName + extension;
            }

            if (file2 != null)
            {
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRootPath, @"Imagini/Masini/");
                var extension = Path.GetExtension(file2.FileName);
                if (obj.Masina.ImagineMasina2 != null)
                {
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Masina.ImagineMasina2.TrimStart('/'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file2.CopyTo(fileStream);
                }
                obj.Masina.ImagineMasina2 = @"/Imagini/Masini/" + fileName + extension;
            }

            if (file3 != null)
            {
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRootPath, @"Imagini/Masini/");
                var extension = Path.GetExtension(file3.FileName);
                if (obj.Masina.ImagineMasina3 != null)
                {
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Masina.ImagineMasina3.TrimStart('/'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file3.CopyTo(fileStream);
                }
                obj.Masina.ImagineMasina3 = @"/Imagini/Masini/" + fileName + extension;
            }

            obj.Masina.TarifPeSaptamana = ((obj.Masina.TarifPeZi * 7) - (10 / (float)100 * obj.Masina.TarifPeZi * 7));
            obj.Masina.TarifPeLuna = (obj.Masina.TarifPeZi * 30) - (15 / (float)100 * obj.Masina.TarifPeZi * 30);

            if (obj.Masina.IdMasina == 0)
            {
                _unitOfWork.Masina.Add(obj.Masina);
                TempData["succes"] = "Masina adaugata cu succes!";
            }
            else
            {
                _unitOfWork.Masina.Update(obj.Masina);
                TempData["succes"] = "Masina modificata cu succes!";
            }
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }
        return View(obj);
    }

    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var listaMasini = _unitOfWork.Masina.GetAll(includeProperties: "MarcaMasina");
        return Json(new { data = listaMasini });
    }

    //POST
    [HttpDelete]
    public IActionResult Stergere(int? id)
    {
        var obj = _unitOfWork.Masina.GetFirstOrDefault(u => u.IdMasina == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Nu s-a putut efectua stergerea!" });
        }

        var oldImagePath1 = Path.Combine(_hostEnvironment.WebRootPath, obj.ImagineMasina1.TrimStart('/'));
        if (System.IO.File.Exists(oldImagePath1))
        {
            System.IO.File.Delete(oldImagePath1);
        }
        var oldImagePath2 = Path.Combine(_hostEnvironment.WebRootPath, obj.ImagineMasina2.TrimStart('/'));
        if (System.IO.File.Exists(oldImagePath2))
        {
            System.IO.File.Delete(oldImagePath2);
        }
        var oldImagePath3 = Path.Combine(_hostEnvironment.WebRootPath, obj.ImagineMasina3.TrimStart('/'));
        if (System.IO.File.Exists(oldImagePath3))
        {
            System.IO.File.Delete(oldImagePath3);
        }

        _unitOfWork.Masina.Remove(obj);
        _unitOfWork.Save();
        TempData["succes"] = "Masina eliminata!";
        return Json(new { success = true, message = "Stergerea s-a efectuat cu succes!" });
    }
    #endregion
}

InchirieriMasini/Views/Shared/_Layout.cshtml
@using InchirieriMasini.Utility
@using Microsoft.AspNetCore.Identity


@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InchirieriMasini</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/styles.css" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/TemaBootsWatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InchirieriMasini.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="mx-4 fs-4" asp-area="Client" asp-controller="Home" asp-action="Index" style="text-decoration:none;"> RentalX </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
            <a class="nav-link" asp-area="Client" asp-controller="Home" asp-action="Index">Home</a>
            <span class="visually-hidden">(current)</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="Client" asp-controller="Home" asp-action="CatalogMasini">Catalog</a>
        </li>
         @if(SignInManager.IsSignedIn(User) && User.IsInRole(StaticData.Role_User)){
        <li class="nav-item">
          <a class="nav-link" asp-area="Client" asp-controller="Home" asp-action="IstoricComenzi">Istoric comenzi</a>
        </li>
        }
        @if(User.IsInRole(StaticData.Role_Manager))
        {
        <li class="nav-item">
          <a class="nav-link" asp-area="Manager" asp-controller="MarcaMasina" asp-action="Index">Marci</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="Manager" asp-controller="Masina" asp-action="Index">Masini</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="Manager" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
        </li>
        }
      </ul>
      <div>
        <partial name="_LoginPartial"/>
        </div>
    </div>
  </div>
</nav>
       
    </header>
    <div>
        <main role="main">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>

<div class="container">
  <footer>
    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
      <p class="fs-3"> RentalX </p>
      <p>© 2022 RentalX. All rights reserved.</p>
    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a  href="#"><svg style="color:black;" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-dark" href="#"><svg  width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-dark" href="#"><svg  width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
    </div>
  </footer>
</div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InchirieriMasini/Views/Shared/_LayoutEmpty.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InchirieriMasini</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/styles.css" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/TemaBootsWatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InchirieriMasini.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    
</head>
<body>
    <header>
       
       
    </header>
    <div class="mainbg">
        <main role="main">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InchirieriMasini/Views/Shared/_Notifications.cshtml
@if (TempData["succes"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
           toastr.success('@TempData["succes"]')    
    </script>
}

@if (TempData["error"] != null)
{
     <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
           toastr.success('@TempData["error"]')    
    </script>
}