InchirieriMasini/Areas/Manager/Controllers/MarcaMasinaController.cs
using InchirieriMasini.DataAccess.Data;
using InchirieriMasini.DataAccess.Repository.IRepository;
using InchirieriMasini.Models;
using InchirieriMasini.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InchirieriMasini.Areas.Manager.Controllers
{
    [Area("Manager")]
    [Authorize(Roles = StaticData.Role_Manager)]

    public class MarcaMasinaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public MarcaMasinaController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<MarcaMasina> objListaMarci = _unitOfWork.MarcaMasina.GetAll();
            return View(objListaMarci);
        }
        //GET
        public IActionResult Creare()
        {

            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Creare(MarcaMasina obj)
        {
            if (obj.DenumireMarca == obj.LogoURL)
            {
                ModelState.AddModelError("logourl", "Ai uitat sa precizezi tipul fisierului!");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.MarcaMasina.Add(obj);
                _unitOfWork.Save();
                TempData["succes"] = "Marca creata!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        public IActionResult Editare(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var marcaDb = _unitOfWork.MarcaMasina.GetFirstOrDefault(u => u.IdMarca == id);
            if (marcaDb == null)
            {
                return NotFound();
            }
            return View(marcaDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editare(MarcaMasina obj)
        {
            if (obj.DenumireMarca == obj.LogoURL)
            {
                ModelState.AddModelError("logourl", "Ai uitat sa precizezi tipul fisierului!");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.MarcaMasina.Update(obj);
                _unitOfWork.Save();
                TempData["succes"] = "Marca modificata!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        public IActionResult Stergere(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var marcaDb = _unitOfWork.MarcaMasina.GetFirstOrDefault(u => u.IdMarca == id);
            if (marcaDb == null)
            {
                return NotFound();
            }
            return View(marcaDb);
        }

        //POST
        [HttpPost, ActionName("Stergere")]
        [ValidateAntiForgeryToken]
        public IActionResult StergerePost(int? id)
        {
            var obj = _unitOfWork.MarcaMasina.GetFirstOrDefault(u => u.IdMarca == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.MarcaMasina.Remove(obj);
            _unitOfWork.Save();
            TempData["succes"] = "Marca strearsa!";
            return RedirectToAction("Index");
        }
    }
}

InchirieriMasini/Areas/Manager/Views/MarcaMasina/Creare.cshtml
@model MarcaMasina

<form method="post">
    <div class="border p-3 mr-4">
        <div class="row pb-2">
            <h2 class="text-primary">Adauga Marca</h2>
            <hr />
        </div>
        <div class="mb-3 ">
            <label asp-for="DenumireMarca"></label>
            <input asp-for="DenumireMarca"/>
            <span asp-validation-for="DenumireMarca" class="text-danger"></span>
        </div>
        <div class="mb-3 ">
            <label asp-for="LogoURL"></label>
            <input asp-for="LogoURL"/>
            <span asp-validation-for="LogoURL" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Adauga</button>
        <a asp-controller="MarcaMasina" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Inapoi
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

InchirieriMasini/Areas/Manager/Views/MarcaMasina/Editare.cshtml
@model MarcaMasina

<form method="post" asp-action="Editare">
    <input asp-for="IdMarca" hidden />
    <div class="border p-3 mr-4">
        <div class="row pb-2">
            <h2 class="text-primary">Modifica Marca</h2>
            <hr />
        </div>
        <div class="mb-3 ">
            <label asp-for="DenumireMarca"></label>
            <input asp-for="DenumireMarca"/>
            <span asp-validation-for="DenumireMarca" class="text-danger"></span>
        </div>
        <div class="mb-3 ">
            <label asp-for="LogoURL"></label>
            <input asp-for="LogoURL"/>
            <span asp-validation-for="LogoURL" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Modifica</button>
        <a asp-controller="MarcaMasina" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Inapoi
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

InchirieriMasini/Areas/Manager/Views/MarcaMasina/Index.cshtml
@model IEnumerable<MarcaMasina>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Marci Disponibile
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="MarcaMasina" asp-action="Creare" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp Adaugare Marca
            </a>
        </div>
    </div>
    <br /><br /><br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Marca
            </th>
            <th>
                Logo
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.DenumireMarca
                </td>
                <td width="30%">
                    <img width=100px src="~/Imagini/MarciMasini/@obj.LogoURL">
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="MarcaMasina" asp-action="Editare" asp-route-id="@obj.IdMarca" class="btn btn-primary mx-2">
                            <i class="bi bi-pencil-square"></i>Editare
                        </a>
                        <a asp-controller="MarcaMasina" asp-action="Stergere" asp-route-id="@obj.IdMarca" class="btn btn-danger mx-2">
                            <i class="bi bi-trash-fill"></i>Stergere
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

InchirieriMasini/Areas/Manager/Views/MarcaMasina/Stergere.cshtml
@model MarcaMasina

<form method="post" asp-action="Stergere">
    <input asp-for="IdMarca" hidden />
    <div class="border p-3 mr-4">
        <div class="row pb-2">
            <h2 class="text-primary">Sterge Marca</h2>
            <hr />
        </div>
        <div class="mb-3 ">
            <label asp-for="DenumireMarca"></label>
            <input asp-for="DenumireMarca" disabled class="form-control"/>
        </div>
        <div class="mb-3 ">
            <label asp-for="LogoURL"></label>
            <input asp-for="LogoURL" disabled class="form-control"/>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Sterge</button>
        <a asp-controller="MarcaMasina" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Inapoi
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}